apiVersion: v1
kind: Deployment
metadata:
  name: cart
  namespace: robotshop
  labels:
    app.kubernetes.io/name: cart
    app.kubernetes.io/instance: dev
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: cart
    app.kubernetes.io/part-of: robot-shop
    app.kubernetes.io/managed: manual
    app.kubernetes.io/tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cart
      app.kubernetes.io/instance: dev
      app.kubernetes.io/tier: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cart
        app.kubernetes.io/instance: dev
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/component: cart
        app.kubernetes.io/tier: app
    spec:
      selector:
        matchLabels:
        app.kubernetes.io/name: cart
        app.kubernetes.io/instance: dev
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/component: cart
        app.kubernetes.io/tier: app
      containers:
      - name: cart
        image: joindevops/cart:v1
        envFrom:
        - configMapRef:
            name: cart-configmap
        ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: "250m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
---


