apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-configmap
  namespace: robotshop
  labels:
    app.kubernetes.io/name: cart
    app.kubernetes.io/instance: dev
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: cart
    app.kubernetes.io/part-of: robot-shop
    app.kubernetes.io/managed: manual
    app.kubernetes.io/tier: app
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
