apiVersion: v1
kind: ConfigMap
metadata:
  name: user-configmap
  namespace: robotshop
  labels:
    app.kubernetes.io/name: user
    app.kubernetes.io/instance: dev
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: user
    app.kubernetes.io/part-of: robot-shop
    app.kubernetes.io/managed: manual
    app.kubernetes.io/tier: app
data:
  MONGO_URL: "mongodb://mongodb:27017/users"
  REDIS_URL: "redis://redis:6379"
  MONGO: "true"
