apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-configmap
  namespace: robotshop
  labels:
    app.kubernetes.io/name: catalogue
    app.kubernetes.io/instance: dev
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: catalogue
    app.kubernetes.io/part-of: robot-shop
    app.kubernetes.io/managed: manual
    app.kubernetes.io/tier: app
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb-service.robotshop.svc.cluster.local:27017/catalogue"
